package com.ledgerflow.payments.internal.domain;

public enum PaymentState {
  CREATED,
  AUTHORIZING,
  AUTHORIZED,
  DECLINED,
  AUTHORIZATION_RETRY_PENDING,
  AUTHORIZATION_UNKNOWN,
  CAPTURING,
  CAPTURE_CONFIRMED,
  CAPTURE_ACCOUNTED,
  CAPTURE_DECLINED,
  CAPTURE_RETRY_PENDING,
  CAPTURE_UNKNOWN,
  FAILED
}
