apiVersion: v1
kind: ConfigMap
metadata:
  name: ledgerflow-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ledgerflow.labels" . | nindent 4 }}
data:
  LEDGERFLOW_DB_URL: {{ .Values.config.dbUrl | quote }}
  LEDGERFLOW_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  LEDGERFLOW_OAUTH2_AUDIENCE: {{ .Values.config.oauth2Audience | quote }}
  LEDGERFLOW_OAUTH2_ISSUER: {{ .Values.config.oauth2Issuer | quote }}
  LEDGERFLOW_OAUTH2_JWK_SET_URI: {{ .Values.config.oauth2JwkSetUri | quote }}
  LEDGERFLOW_MANAGEMENT_PORT: {{ .Values.managementPort | quote }}
  LEDGERFLOW_HEALTH_PROBE_CACHE_TTL: {{ .Values.config.healthProbeCacheTtl | quote }}
  LEDGERFLOW_DEPLOYMENT_ENVIRONMENT: {{ .Values.config.deploymentEnvironment | quote }}
  LEDGERFLOW_TRACE_SAMPLING_PROBABILITY: {{ .Values.config.traceSamplingProbability | quote }}
  {{- if .Values.config.otlpTracesEndpoint }}
  LEDGERFLOW_OTLP_TRACES_ENDPOINT: {{ .Values.config.otlpTracesEndpoint | quote }}
  {{- end }}
  {{- if .Values.config.otlpLogsEndpoint }}
  LEDGERFLOW_OTLP_LOGS_ENDPOINT: {{ .Values.config.otlpLogsEndpoint | quote }}
  {{- end }}
