import http from "k6/http";
import { SharedArray } from "k6/data";
import { uuidv4 } from "https://jslib.k6.io/k6-utils/1.4.0/index.js";

export const BASE_URL = __ENV.BASE_URL || "http://localhost:18080";

// A pool of tokens, one per authenticated subject, generated by
// performance/scripts/run-experiments.sh into performance/scenarios/tokens.json (git-ignored,
// regenerated every run). A single shared identity trips the application's documented
// per-subject write rate limit (README.md "Create Order API", 60/min by default) well
// below this milestone's realistic throughput targets — that would be a load-generator
// artifact, not a system finding, so every VU picks its own subject from the pool instead
// of every VU sharing one.
const tokens = new SharedArray("tokens", function () {
  return JSON.parse(open("../tokens.json"));
});

export function accessToken() {
  return tokens[(__VU - 1) % tokens.length];
}

// contentionToken()/burstToken() are deliberately NOT here: k6's `open()` only works in the
// init stage (module top-level), and only idempotency-contention.js and burst-traffic.js
// need their dedicated per-scenario token files (contention-token.json / burst-token.json
// respectively) — every other scenario would fail at load time if this shared module also
// tried to open files that only exist for those two runs. Each of those two scenarios reads
// its own token file directly at its own top level instead.

export function createOrder(idempotencyKey, paymentMethodReference, clientReference, token) {
  const correlationId = `perf-${uuidv4()}`;
  return http.post(
    `${BASE_URL}/api/v1/orders`,
    JSON.stringify({
      clientReference: clientReference || `perf-${uuidv4()}`,
      amount: { amountMinor: 259900, currency: "INR" },
      paymentMethodReference: paymentMethodReference || "pm_mock_success",
    }),
    {
      headers: {
        Authorization: `Bearer ${token || accessToken()}`,
        "Content-Type": "application/json",
        "Idempotency-Key": idempotencyKey,
        "X-Correlation-Id": correlationId,
      },
    },
  );
}

export function readOrder(orderId) {
  return http.get(`${BASE_URL}/api/v1/orders/${orderId}`, {
    headers: {
      Authorization: `Bearer ${accessToken()}`,
      "X-Correlation-Id": `perf-${uuidv4()}`,
    },
  });
}

export { uuidv4 };
