package com.ledgerflow.payments.api;

public enum PaymentStatus {
  CREATED,
  AUTHORIZING,
  AUTHORIZED,
  DECLINED,
  AUTHORIZATION_RETRY_PENDING,
  AUTHORIZATION_UNKNOWN,
  CAPTURING,
  CAPTURE_CONFIRMED,
  CAPTURE_ACCOUNTED,
  CAPTURED,
  CAPTURE_DECLINED,
  CAPTURE_RETRY_PENDING,
  CAPTURE_UNKNOWN,
  FAILED
}
